# Generated by Django 3.1.2 on 2021-09-08 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('sub_title', models.TextField(blank=True, null=True)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='')),
                ('blog', models.TextField()),
                ('author', models.CharField(blank=True, max_length=200, null=True)),
                ('author_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('posted_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
