# Generated by Django 3.1.2 on 2021-09-08 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog_app', '0002_auto_20210908_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='banner',
            field=models.ImageField(blank=True, max_length=250, null=True, upload_to='banners/'),
        ),
    ]
