# Generated by Django 4.0.5 on 2022-09-29 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
